# Generated by Django 3.1.2 on 2020-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PLN', 'Planned'), ('PRG', 'In Progress'), ('DON', 'Done')], default='NEW', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('priority', models.CharField(choices=[('MN', 'Minor'), ('MJ', 'Major')], default='MN', max_length=5)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
